### ISSUE TITLE
Pano 

### ISSUE THREAD

**Issue by Dogdive** [skiphansen/panog2_ldr#3]
Support for Rev A

**Comment by Dogdive** [comment]
Sorry about the opening and closing of issues. I am new to github. Anyway, I just got a rev A G2 the other day and I would like to use the panog2_ldr with it, however it seems to be looking for a rev b or c and not the rev a. How can I modify the script to flash this onto it? I also noticed that maybe it can be done with pano_progfpga. To be honest, this is probably (it is) way way over my head but... I got this thing because I thought maybe I could somehow get it to emulate an Apple II, II+ or IIe. I don't have a jtag programmer but it seems that I really need to get one. Any assistance would be appreciated. Thanks, Jeff

**Comment by skiphansen** [comment]
The reason that rev A isn't supported is that I've never seen one and as far as I know no one has ever done anything with one.  I have seem some pictures and read that there were significant changes between the Rev A and the Rev B.  My advice would be to keep it as a paper weight and get a G2 rev B or C.  They are still readily available on ebay.

To do development you probably really do need a JTAG debugger.  The main reason for the loader is that's it's almost impossible to get to the JTAG connector on the DZ22 without breaking it, but it's easy on a G2.

If you get a JTAG we can also try to figure it out if you are game.

See the Wiki https://github.com/tomverbeure/panologic-g2/wiki and drop by https://gitter.im/panologic/community for more information.

**Comment by Dogdive** [comment]
Thank you for the info. I really appreciate you taking a minute to answer. I had actually ordered what was listed as a G1. I could see that it had a dvi to vgi adapted on it so I knew it was a G2. It was $14.99 with free shipping so it's not really a loss. I didn't expect it to be a rev a. I have found like less than zero info on the rev a. As I read more it seems like a G1 might really be the better thing to get. What is your opinion on that?

**Comment by Dogdive** [comment]
Ok. Progress. I was the problem. 32bit on my linux wasn't enabled. Then I sort of goofed around with it for 3 hours. I could get it to erase but not flash and that was after looking at your script a thousand times and replacing a bunch of stuff and then I decided the problem was my install of EndeavourOS. Installed Ubuntu and enabled 32bit and it worked. I can telnet into it. I need something to flash into it now. I was looking at your panog2_nes but my back is killing me from sitting at the computer. So that will have to happen another day.
