### ISSUE TITLE
DZ22-2 : does not respond after flashing firmware.

### ISSUE THREAD

**Issue by gulamf** [skiphansen/panog2_ldr#4]
Hi
I have flashed the loader onto it using JTAG, but when I power cycle it, it does not appear on the network.
It seems the network is not activated as the lights on the network adapter do not light up.
Any help is appreciated.
Thanks

Oututput from the flashing process is as follows

gulamf@gulamf-XPS-13-9343:~/development/panog2_ldr$ make PLATFORM=pano-g2 prog_fpga 
make -C fpga prog_fpga
make[1]: Entering directory '/home/gulamf/development/panog2_ldr/fpga'
xc3sprog -c xpc -v -I/home/gulamf/development/panog2_ldr/pano/cores/xc3sprog/xc6slx150.bit /home/gulamf/development/panog2_ldr/prebuilt/pano-g2.bit:w:4718592
XC3SPROG (c) 2004-2011 xc3sprog project $Rev$ OS: Linux
Free software: If you contribute nothing, expect nothing!
Feedback on success/failure/enhancement requests:
	http://sourceforge.net/mail/?group_id=170565 
Check Sourceforge for updates:
	http://sourceforge.net/projects/xc3sprog/develop

Using built-in device list
Using built-in cable list
firmware version = 0x0012 (18)
CPLD version = 0x0012 (18)
JTAG chainpos: 0 Device IDCODE = 0x3401d093	Desc: XC6SLX150
Created from NCD file: top.ncd;UserID=0xFFFFFFFF
Target device: 6slx150fgg484
Created: 2019/11/09 17:21:29
Bitstream length: 9415568 bits
DNA is 0xd98651c96521a000
done. Programming time 5208.1 ms
JEDEC: 20 20 0x18 0x00
Found Numonyx M25P Device, Device ID 0x2018
256 bytes/page, 65536 pages = 16777216 bytes total 
Created from NCD file: fpga_routed.ncd;HW_TIMEOUT=FALSE;UserID=0xFFFFFFFF
Target device: 6slx100fgg484
Created: 2023/02/10 20:12:08
Bitstream length: 15792832 bits
Erasing sector 26/26....Writing data page   7711/  7712 at flash page  26143..
Maximum erase time 1774.8 ms, Max PP time 177483 us
Verifying page   7712/  7712 at flash page  26144
Verify: Success!
USB Read Transactions: 31459 Write Transactions: 243382 Control Transaction 243391
make[1]: Leaving directory '/home/gulamf/development/panog2_ldr/fpga'

**Comment by skip-dt** [comment]
Congratulations in opening the DZ22 and hooking up JTAG ... my fingers hurt just thinking back to when I took mine apart !!
Stupid question, was it working with the stock bit file?  Did you flash anything else before panog2_ldr?

**Comment by gulamf** [comment]
Yes It was a hard taking it apart. I had no choice after bricking it playing around with the pano_progfpga.
I think i used the flashfpga optiion or something like it; and had the sinking feeling when I saw the message that the flash was being erased! 

It was visible on the network with the stock firmware.
There would be a response from the unit if used the -d option.
Thanks

**Comment by skip-dt** [comment]
"playing around with the pano_progfpga" <- so it worked initially after programming it over Ethernet?

If all of flash was erased then make prog_fpga won't work because that assumes the multiboot header is still in place.

Try programming [pano-g2.bit](https://github.com/skiphansen/panog2_ldr/blob/master/prebuilt/pano-g2.bit) into offset 0.

````
xc3sprog -c xpc -v -I/home/gulamf/development/panog2_ldr/pano/cores/xc3sprog/xc6slx150.bit /home/gulamf/development/panog2_ldr/prebuilt/pano-g2.bit:w:0
````

Chatting on https://gitter.im/panologic/community might be easier than posting a bunch of messages here...

**Comment by gulamf** [comment]
That fixed it.
Thank you very much!!
