### ISSUE TITLE
About installation....

### ISSUE THREAD

**Issue by mopplayer** [skiphansen/panog2_ldr#5]
Hi,
I am installing this flasher to my Rev. B Pano logic.
But it seems to be hanging.

The Pano logic is lighting blue, and its Ethernet port is blinking.

Ubuntu 20.04 terminal:

```
...
Writing the Start writing multiboot image! consumed 89.072472 seconds
reading flash & verifing 
(hangs)
```

Is this status normal? 
Any suggestion will be appreciated.

**Comment by mopplayer** [comment]
Oh, I have got the result...

```
Test has PASSED 
Disconnecting audio...
Start writing multiboot image! Image Verified, validation consumed 4330.399902 seconds
Disconnected
Pano_ldr installed, power cycle the Pano to start it
```
It cost 72 minutes. 

Does install_rev_b have the source code?

Moreover, when I telnet to the Pano logic.
The device is disconnected from LAN and the led is not lighting.
Is this status normal?
Any suggestion will be appreciated.

Thank you very much.

**Comment by skiphansen** [comment]
I've never seen it take that long, but I'm glad it completed.

Source for install_ref_b is not available because it is a binary that was patched by pano_progfpga(https://github.com/skiphansen/pano_progfpga).

After you power cycle the Pano it should pull an IP address from your router, the IP address will probably be different that it was previously.  You should be able to telnet into the new address.

**Comment by mopplayer** [comment]
@skiphansen Thank you for the information on that source code.

Yes, I have updated this situation clearly after that time, and mentioned a solution, which can be updated to the README.md.

I could find the right address, and ping it successfully.
When I telneted Pano logic (with green blinking LED), that Pano logic device was freezed to respond, button LED turned to blank. I had to power cycle it.

I have tried many times, got the same result, I suspected other problems on the router.
Try to change many settings of my router, including port forwarding.

Finally, I found that critical problem, the firewall.
Usually, the firewall, specifically SPI firewall, will block suspect packets outside the local network, but it seems the same rule to be occupied in the local network.

[Firewall](https://imgur.com/rZGFW0X)

When I  turn off the SPI firewall, I can connect Pano logic with telnet successfully.
I think that flashing panog2_ldr takes 72 minutes, which is also the same problem.

It would be thankful to update the README.md to mention users the possible issues.

**Comment by skiphansen** [comment]
Thanks for letting me know, I'll update the README when I get a chance.  I would never have expected a firmware to mess with traffic between two devices on the same LAN.  I don't even know how that's possible unless your PC was connected via WiFi rather than hardwired Ethernet.

**Comment by mopplayer** [comment]
Hi @skiphansen,

The firewall takes effect either Ethernet or Wifi, so that symptoms are that same. I have tried many times, moreover, the firmware and chip of newer router devices  (Wifi 6 up), the hardware firewall will be more powerful. Might the old router devices have no influence.

**Comment by skiphansen** [comment]
I've updated the README.
